spring:
  application:
    name: file-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-d57aoi1r0fns73fjak70-a.singapore-postgres.render.com:5432/file_service_1eai?sslmode=require
    username: file_service_1eai_user
    password: Q95EyOe6YDjh4UBmQPe5hHcpmxCf20j3

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

#  datasource:
#    url: jdbc:mariadb://10.210.40.40:3306/file_service
#    username: kyc_uat
#    password: ILoveKYC
#    driver-class-name: org.mariadb.jdbc.Driver
#    hikari:
#      maximum-pool-size: 5
#      minimum-idle: 2
#
#  jpa:
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MariaDBDialect
#        format_sql: false
#        show_sql: false
#        jdbc:
#          batch_size: 20
#          batch_versioned_data: true
#        order_inserts: true
#        order_updates: true
#    open-in-view: false

app:
  r2:
    endpoint:
    accessKey:
    secretKey:
    bucket:
    presignPutExpirySeconds: 600
    publicBaseUrl:
