spring:
  application:
    name: file-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-d57aoi1r0fns73fjak70-a.singapore-postgres.render.com:5432/file_service_1eai?sslmode=require
    username: file_service_1eai_user
    password: Q95EyOe6YDjh4UBmQPe5hHcpmxCf20j3

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

app:
  r2:
    endpoint:
    accessKey:
    secretKey:
    bucket:
    presignPutExpirySeconds: 600
    publicBaseUrl:
    presignExpiry:

  cleanup:
    pending-assets-threshold-minutes: 60
    cron: 0 0 * * * *

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    default-models-expand-depth: 3
    default-model-expand-depth: 3
  show-actuator: false
